"""candidate_intelligence_profile

Revision ID: 0baf4c7a73d8
Revises: eb5165630283
Create Date: 2026-06-20 05:52:31.921203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0baf4c7a73d8'
down_revision: Union[str, None] = 'eb5165630283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('intelligence_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'intelligence_profile')
    # ### end Alembic commands ###
