"""job_metrics

Revision ID: 303057991824
Revises: 0baf4c7a73d8
Create Date: 2026-06-21 07:44:52.204432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303057991824'
down_revision: Union[str, None] = '0baf4c7a73d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('llm_calls', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('eval_time_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'eval_time_seconds')
    op.drop_column('jobs', 'llm_calls')
    # ### end Alembic commands ###
