"""candidate pools

Revision ID: f2792ec743a3
Revises: be3ede912c66
Create Date: 2026-06-18 09:48:15.485136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2792ec743a3'
down_revision: Union[str, None] = 'be3ede912c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_pools_owner_id'), 'candidate_pools', ['owner_id'], unique=False)
    op.add_column('candidates', sa.Column('pool_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_candidates_owner_external', table_name='candidates')
    op.create_index(op.f('ix_candidates_pool_id'), 'candidates', ['pool_id'], unique=False)
    op.create_unique_constraint('uq_pool_candidate', 'candidates', ['pool_id', 'external_id'])
    op.create_foreign_key(None, 'candidates', 'candidate_pools', ['pool_id'], ['id'])
    op.add_column('jobs', sa.Column('candidate_pool_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_jobs_candidate_pool_id'), 'jobs', ['candidate_pool_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'candidate_pools', ['candidate_pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_candidate_pool_id'), table_name='jobs')
    op.drop_column('jobs', 'candidate_pool_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint('uq_pool_candidate', 'candidates', type_='unique')
    op.drop_index(op.f('ix_candidates_pool_id'), table_name='candidates')
    op.create_index('ix_candidates_owner_external', 'candidates', ['owner_id', 'external_id'], unique=False)
    op.drop_column('candidates', 'pool_id')
    op.drop_index(op.f('ix_candidate_pools_owner_id'), table_name='candidate_pools')
    op.drop_table('candidate_pools')
    # ### end Alembic commands ###
